spring:
  application:
    name: badgeservice
  profiles:
    active: dev
  config:
    #service-registry:
    # auto-registration:
    #  register-management: on
    import: optional:configserver:http://localhost:10003

  zipkin:
    baseurl: http://localhost:9411/
    sender:
      type: web # les requetes seront envoyes en HTTP
    sleuth:
      sampler:
        probability: 1.0
  data:
    mongodb:
      database: base
      host: localhost
      port: 27019
      username: root
      password: root
      authentication-database: admin
management:
  endpoints:
    web:
      exposure:
        include:
          env,health,
          info,metrics,
          loggers,mappings, prometheus

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    metadata-map:
      prometheus.scrape: "true"
      prometheus.path: "/actuator/prometheus"
      prometheus.port: "${management.server.port}"

logging:
  level:
    org.springframework.web: INFO
server:
  port: 10025