spring:
  application:
    name: compositestatistique
  cloud:
    config:
      service-registry:
        auto-registration:
          register-management: on
  config:
    import: optional:configserver:http://localhost:10003

  zipkin:
    baseurl: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include:
          env,health,
          info,metrics,
          loggers,mappings, prometheus
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    metadata-map:
      prometheus.scrape: "true"
      prometheus.path: "/actuator/prometheus"
      prometheus.port: "${management.server.port}"
logging:
  level:
    org.springframework.web: INFO


server:
  port: 10042